<script setup lang="ts">
const route = useRoute();
const config = useRuntimeConfig();
const { token, authHeaders } = useSqjAuth();
const report = ref<any>();
const catalog = ref<any[]>([]);
const error = ref("");
const activeSection = ref("summary");
const question = ref("");
const messages = ref([{ role: "assistant", text: "我只依据当前已购买报告内容回答，并提示证据范围与数据日期。" }]);

const purchasedCodes = computed(() => new Set((report.value?.sections || []).map((item: any) => item.product.code)));
const allSections = computed(() => catalog.value.map((product) => ({
  product,
  purchased: purchasedCodes.value.has(product.code),
  sourceState: report.value?.sections.find((item: any) => item.product.code === product.code)?.sourceState,
})));

async function load() {
  if (!token.value) return navigateTo({ path: "/login", query: { redirect: route.fullPath } });
  try {
    [report.value, catalog.value] = await Promise.all([
      $fetch(`${config.public.apiBase}/reports/${route.params.id}`, { headers: authHeaders() }),
      $fetch<any[]>(`${config.public.apiBase}/report-products`),
    ]);
  } catch (e: any) { error.value = e?.data?.message || "报告不存在、尚未支付或无权访问"; }
}

onMounted(async () => {
  await load(); await nextTick();
  const root = document.querySelector(".report-document");
  const observer = new IntersectionObserver((entries) => {
    const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0];
    if (visible) activeSection.value = visible.target.id.replace("section-", "");
  }, { root, threshold: [0.2, 0.55] });
  document.querySelectorAll("[id^='section-']").forEach((node) => observer.observe(node));
});

function jumpTo(code: string) { document.getElementById(`section-${code}`)?.scrollIntoView({ behavior: "smooth" }); }
function printReport() { window.print(); }
function dataOf(section: any) { return section?.sourceState?.data || section?.sourceState || {}; }

const labels: Record<string, string> = {
  legalName:"英文法定名称",localName:"当地语言名称",registrationNumber:"企业注册号",country:"注册国家 / 地区",legalForm:"法律形式",status:"经营状态",foundedAt:"成立日期",registeredCapital:"注册资本",registeredAddress:"注册地址",industry:"所属行业",
  contacts:"公开联系方式",operatingAddresses:"经营地址",shareholders:"直接股东",ultimateBeneficialOwners:"最终受益人",disclosure:"披露完整度",officers:"董事与管理层",parent:"直接母公司",affiliates:"关联企业",
  currency:"财务币种",periods:"近三年财务数据",auditOpinion:"审计意见",summary:"风险记录汇总",records:"司法与经营记录",complianceFlags:"合规提示",screenedAt:"筛查时间",lists:"筛查名单范围",matches:"名单命中",conclusion:"筛查结论",
  listing:"上市状态",financingRounds:"融资事件",mergersAndAcquisitions:"并购交易",patents:"专利概况",trademarks:"商标概况",domains:"公开域名",cyberRisk:"网络风险",name:"名称",ownershipPct:"持股比例",nationality:"国籍",role:"职务",relationship:"关系",year:"年度",revenue:"营业收入",netIncome:"净利润",totalAssets:"总资产",totalLiabilities:"总负债",courtCases:"诉讼案件",enforcementRecords:"执行记录",administrativePenalties:"行政处罚",filedAt:"立案日期",announcedAt:"披露日期",amount:"金额",investors:"投资方",applications:"申请量",grants:"授权量",active:"有效量",registered:"注册量",rating:"风险等级",exposedServices:"暴露服务",address:"地址",isRegisteredAddress:"是否注册地址",value:"公开值",
};
function labelFor(key: string) { return labels[key] || key; }
function valueText(value: any): string {
  if (value === null || value === undefined || value === "") return "未披露";
  if (typeof value === "boolean") return value ? "是" : "否";
  if (typeof value === "number") return value.toLocaleString("zh-CN");
  if (Array.isArray(value)) return value.length ? value.map((item) => typeof item === "object" ? Object.entries(item).filter(([key]) => key !== "confidence").map(([key, child]) => `${labelFor(key)}：${valueText(child)}`).join("；") : valueText(item)).join("\n") : "未发现记录";
  if (typeof value === "object") return Object.entries(value).map(([key, child]) => `${labelFor(key)}：${valueText(child)}`).join("；");
  return String(value).replaceAll("_", " ").replace("ACTIVE", "在营").replace("CLOSED", "已结案").replace("SETTLED", "已和解").replace("UNQUALIFIED", "标准无保留意见").replace("NO MATCH FOUND IN DECLARED TEST SCOPE", "在本次声明的核查范围内未发现命中");
}
function facts(section: any) { return Object.entries(dataOf(section)).filter(([key]) => !["classification", "sourceUpdatedAt"].includes(key)).map(([key, value]) => ({ label: labelFor(key), value: valueText(value) })); }
function sourceDate(section: any) { const raw = dataOf(section)?.sourceUpdatedAt || report.value?.generatedAt; return raw ? new Date(raw).toLocaleString("zh-CN", { hour12: false }) : "生成时点"; }
function ask(text?: string) {
  const prompt = (text || question.value).trim(); if (!prompt) return;
  messages.value.push({ role: "user", text: prompt });
  messages.value.push({ role: "assistant", text: `基于当前已购的 ${report.value.products.length} 个模块：主体识别已完成；重点建议核对股权控制、财务趋势及司法合规信息。该结论仅覆盖报告生成时点。` });
  question.value = "";
}
</script>

<template>
  <main v-if="error" class="blocked"><h1>无法打开报告</h1><p>{{ error }}</p><NuxtLink to="/">返回首页</NuxtLink></main>
  <div v-else-if="report" class="report-app">
    <header class="report-topbar">
      <NuxtLink class="report-brand" to="/"><img src="/sqj-lockup-v4.svg" alt="商情据" /></NuxtLink>
      <div class="report-title"><strong>{{ report.company.name }}</strong><small v-if="report.company.localName !== report.company.name">{{ report.company.localName }}</small><span>企业调查报告 · V1 · 数据截止 {{ new Date(report.generatedAt).toLocaleString("zh-CN", { hour12: false }) }}</span></div>
      <div class="report-actions"><NuxtLink :to="`/company/${report.company.id}`">增购模块</NuxtLink><button @click="printReport">打印 / 保存 PDF</button><NuxtLink class="primary" to="/account">我的报告</NuxtLink></div>
    </header>
    <main class="report-layout">
      <aside class="report-toc"><div class="toc-label">报告目录</div><nav>
        <button :class="{ active: activeSection === 'summary' }" @click="jumpTo('summary')"><span>00</span><strong>执行摘要</strong><i>›</i></button>
        <button v-for="section in allSections" :key="section.product.code" :class="{ active: activeSection === section.product.code, locked: !section.purchased }" @click="jumpTo(section.product.code)"><span>{{ section.product.code }}</span><strong>{{ section.product.name }}</strong><i>{{ section.purchased ? "›" : "锁" }}</i></button>
      </nav><div class="toc-legend"><strong>数据状态</strong><span><i class="ok"></i>已购并完成核查</span><span><i></i>未购章节仅显示名称</span></div></aside>
      <article class="report-document">
        <section class="report-cover"><div class="cover-top"><span>商情据 · 企业调查报告</span><span>{{ report.id }}</span></div><div class="cover-main"><span>GLOBAL ENTERPRISE DUE DILIGENCE</span><h1>{{ report.company.name }}</h1><h2 v-if="report.company.localName && report.company.localName !== report.company.name">{{ report.company.localName }}</h2><p>{{ report.company.countryName || report.company.country }} · {{ report.company.registrationNumber }}</p><div class="cover-status"><div><span>报告版本</span><strong>V1</strong></div><div><span>已购模块</span><strong>{{ report.products.length }} / 10</strong></div><div><span>生成方式</span><strong>自动化标准版</strong></div></div></div><div class="cover-foot"><span>本报告为 Mock 示例数据，不构成法律、审计、投资或制裁专业意见。</span><span>{{ new Date(report.generatedAt).toLocaleDateString("zh-CN") }}</span></div></section>
        <section id="section-summary" class="report-section"><div class="section-number">00</div><header><span>EXECUTIVE SUMMARY</span><h2>执行摘要</h2><p>以下内容明确区分报告事实、规则提示和 AI 归纳，重要结论均可回溯至已购买模块与数据日期。</p></header><div class="summary-grid"><article><em class="fact">报告事实</em><strong>主体识别已完成</strong><p>已按名称、国家、注册号与地址确认本次调查主体。</p><button @click="jumpTo('M01')">查看主体证据 →</button></article><article><em class="rule">规则提示</em><strong>合规筛查按时点完成</strong><p>无记录代表本次范围内未发现，不代表未来永久无风险。</p><button @click="jumpTo('M08')">查看筛查范围 →</button></article><article><em class="ai">AI 归纳</em><strong>建议持续核验</strong><p>重点关注财务数据缺口、控制权变化及经营风险动态。</p><button @click="ask('根据本报告生成合作前补充核查清单')">生成核查清单 →</button></article></div><div class="risk-overview"><div><span>高优先级风险</span><strong>0</strong><small>基于已购模块</small></div><div><span>需人工关注</span><strong>2</strong><small>数据缺口与待核对</small></div><div><span>已购模块</span><strong>{{ report.products.length }}</strong><small>已完成数据汇总</small></div><div><span>未购买</span><strong>{{ 10 - report.products.length }}</strong><small>AI 无权读取正文</small></div></div></section>
        <section v-for="section in allSections" :id="`section-${section.product.code}`" :key="section.product.code" class="report-section" :class="{ locked: !section.purchased }"><template v-if="section.purchased"><div class="section-number">{{ section.product.code.slice(1) }}</div><header><span>{{ section.product.code }} · VERIFIED MODULE</span><h2>{{ section.product.name }}</h2><p>{{ section.product.summary }}</p></header><div class="section-state"><b>{{ section.sourceState?.dataState || section.product.dataState }}</b><span>{{ section.product.coverage }}覆盖 · 已保存报告证据</span></div><div class="evidence-table"><div v-for="fact in facts(section)" :key="fact.label"><span>{{ fact.label }}</span><strong>{{ fact.value }}</strong></div></div><div class="source-note"><div><i>源</i><span><strong>商情据标准化数据层（Mock 示例）</strong><small>数据日期 {{ sourceDate(section) }} · 报告版本 V1</small></span></div><b>来源可追溯</b></div></template><template v-else><div class="locked-content"><span>锁</span><div><h2>{{ section.product.code }} {{ section.product.name }}</h2><p>本次订单未购买该模块，报告不展示正文，AI 也无权读取。</p></div><NuxtLink :to="`/company/${report.company.id}`">增购模块</NuxtLink></div></template></section>
        <section class="report-disclaimer"><strong>数据与责任说明</strong><p>当前报告使用 Mock/示例数据验证完整业务流程。正式数据接入后将保留供应商、原始来源、采集日期、标准化版本、报告版本和引用位置；资料不足时不作推测。报告不支持公开外链分享。</p></section>
      </article>
      <aside class="ai-panel"><header><span>AI</span><div><strong>AI 调查员</strong><small>仅阅读当前报告与授权模块</small></div></header><div class="ai-context"><b>当前上下文</b><span>{{ report.company.name }} · V1</span></div><div class="suggestions"><button @click="ask('这家公司最值得关注的风险是什么？')">最值得关注的风险</button><button @click="ask('生成合作前核查清单')">合作前核查清单</button></div><div class="messages"><article v-for="(message, index) in messages" :key="index" :class="message.role"><b>{{ message.role === 'assistant' ? 'AI' : '我' }}</b><p>{{ message.text }}</p></article></div><form @submit.prevent="ask()"><textarea v-model="question" placeholder="询问当前报告内容…"></textarea><button type="submit">发送</button></form></aside>
    </main>
  </div>
</template>

<style scoped>
:global(*){box-sizing:border-box}:global(html,body,#__nuxt){margin:0;min-height:100%;font-family:Inter,"PingFang SC","Microsoft YaHei",sans-serif;color:#142b26}:global(a){color:inherit;text-decoration:none}:global(button){font:inherit}.blocked{max-width:600px;margin:100px auto;padding:42px;background:#fff;border-radius:20px;text-align:center}.blocked a{color:#078866;font-weight:800}
.report-app{height:100vh;overflow:hidden;background:#eef3f2}.report-topbar{display:grid;grid-template-columns:255px 1fr auto;align-items:center;height:68px;padding:0 20px;background:#fff;border-bottom:1px solid #dce6e3}.report-brand{display:flex;align-items:center;gap:10px}.report-brand>b{font-size:27px;letter-spacing:-3px;color:#06332c}.report-brand>span{display:grid}.report-brand strong{font-size:17px}.report-brand small{font-size:9px;color:#6e817b}.report-title{display:grid;justify-items:center;gap:2px}.report-title strong{font-size:13px}.report-title small{font-size:11px}.report-title span{font-size:9px;color:#7c8b87}.report-actions{display:flex;gap:7px;align-items:center}.report-actions a,.report-actions button{min-height:36px;padding:0 12px;border:1px solid #d9e3df;background:#fff;border-radius:7px;font-size:10px;cursor:pointer}.report-actions a{display:grid;place-items:center}.report-actions .primary{color:#fff;background:#092f2a;border-color:#092f2a}
.report-layout{display:grid;grid-template-columns:235px minmax(620px,1fr) 350px;height:calc(100vh - 68px)}.report-toc{overflow:auto;padding:18px 14px 80px;background:#fff;border-right:1px solid #dce6e3}.toc-label{padding:10px 8px 16px;font-size:12px;font-weight:850;border-bottom:1px solid #e4ebe8}.report-toc nav{display:grid;gap:3px;margin-top:10px}.report-toc nav button{display:grid;grid-template-columns:28px 1fr auto;gap:6px;align-items:center;width:100%;padding:10px 8px;border:0;border-radius:7px;background:transparent;text-align:left;cursor:pointer}.report-toc nav button:hover,.report-toc nav button.active{background:#e4f5ef}.report-toc button span{color:#84938e;font-size:9px}.report-toc button strong{font-size:10px}.report-toc button i{font-style:normal;color:#87958f}.report-toc button.locked{opacity:.54}.toc-legend{display:grid;gap:8px;margin-top:20px;padding:14px;background:#f3f7f6;border-radius:8px;font-size:9px}.toc-legend span{display:flex;gap:7px;align-items:center;color:#75847f}.toc-legend i{width:7px;height:7px;border-radius:50%;background:#aab6b2}.toc-legend i.ok{background:#0aa77e}
.report-document{overflow-y:auto;padding:34px max(30px,5vw) 120px;scroll-behavior:smooth}.report-cover{min-height:700px;display:flex;flex-direction:column;justify-content:space-between;padding:46px;background:#082d29;color:#fff;box-shadow:0 16px 40px #17383120}.cover-top,.cover-foot{display:flex;justify-content:space-between;color:#8ea09b;font-size:8px;letter-spacing:.1em}.cover-main{padding:70px 0}.cover-main>span{color:#f0b44b;font-size:10px;letter-spacing:.18em}.cover-main h1{max-width:680px;margin:18px 0 12px;font-family:"Songti SC",serif;font-size:50px;line-height:1.12}.cover-main h2{margin:0 0 14px;font-size:25px}.cover-main>p{color:#b7c6c1;font-size:13px}.cover-status{display:grid;grid-template-columns:repeat(3,1fr);max-width:600px;margin-top:80px;border-top:1px solid #ffffff25}.cover-status div{display:grid;gap:7px;padding:18px 18px 0 0}.cover-status div+div{padding-left:18px;border-left:1px solid #ffffff25}.cover-status span{color:#91a29d;font-size:8px}.cover-status strong{font-size:12px}
.report-section{position:relative;margin-top:24px;padding:48px 50px;background:#fff;box-shadow:0 10px 30px #1738310d;scroll-margin-top:18px}.section-number{position:absolute;top:38px;right:45px;color:#e0e8e5;font-family:"Songti SC",serif;font-size:48px}.report-section>header>span{color:#088766;font-size:8px;font-weight:850;letter-spacing:.14em}.report-section>header h2{margin:8px 0;font-family:"Songti SC",serif;font-size:31px}.report-section>header p{max-width:620px;margin:0;color:#6c7d77;font-size:10px;line-height:1.7}.summary-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:28px}.summary-grid article{display:flex;flex-direction:column;min-height:195px;padding:17px;background:#f3f7f6;border-top:3px solid #079e78}.summary-grid article:nth-child(2){border-color:#e4a638}.summary-grid article:nth-child(3){border-color:#7c5ce2}.summary-grid em{width:max-content;padding:4px 7px;border-radius:4px;font-size:8px;font-style:normal;font-weight:850}.summary-grid .fact{color:#087769;background:#dcf4ec}.summary-grid .rule{color:#90610b;background:#fff1d0}.summary-grid .ai{color:#6548b8;background:#eee9ff}.summary-grid strong{margin:15px 0 7px;font-size:12px}.summary-grid p{margin:0;color:#6c7d77;font-size:9px;line-height:1.6}.summary-grid button{margin-top:auto;padding:0;border:0;background:transparent;color:#087f62;font-size:8px;text-align:left;cursor:pointer}.risk-overview{display:grid;grid-template-columns:repeat(4,1fr);margin-top:18px;border:1px solid #dfe7e4}.risk-overview div{display:grid;gap:4px;padding:15px}.risk-overview div+div{border-left:1px solid #dfe7e4}.risk-overview span,.risk-overview small{color:#7c8985;font-size:8px}.risk-overview strong{font-size:20px}
.section-state{display:flex;gap:8px;align-items:center;margin-top:16px}.section-state b{padding:5px 8px;color:#067e61;background:#def5ed;border-radius:99px;font-size:8px}.section-state span{color:#75857f;font-size:8px}.evidence-table{display:grid;grid-template-columns:repeat(2,1fr);margin-top:28px;border-top:1px solid #dfe7e4;border-left:1px solid #dfe7e4}.evidence-table>div{display:grid;gap:7px;min-height:78px;padding:14px;border-right:1px solid #dfe7e4;border-bottom:1px solid #dfe7e4}.evidence-table span{color:#75847f;font-size:9px}.evidence-table strong{white-space:pre-line;font-size:11px;line-height:1.6;overflow-wrap:anywhere}.source-note{display:flex;justify-content:space-between;align-items:center;margin-top:18px;padding:13px;background:#f3f7f6}.source-note>div{display:flex;gap:9px;align-items:center}.source-note i{display:grid;place-items:center;width:28px;height:28px;color:#fff;background:#08906d;border-radius:8px;font-size:9px;font-style:normal}.source-note span{display:grid;gap:3px}.source-note strong{font-size:9px}.source-note small{color:#75847f;font-size:8px}.source-note>b{color:#07805f;font-size:8px}.report-section.locked{min-height:130px;padding:28px 35px}.locked-content{display:grid;grid-template-columns:auto 1fr auto;gap:15px;align-items:center;color:#7f8d88}.locked-content>span{display:grid;place-items:center;width:32px;height:32px;background:#edf2f0;border-radius:50%;font-size:8px}.locked-content h2{margin:0 0 5px;font-size:14px}.locked-content p{margin:0;font-size:9px}.locked-content a{padding:8px 11px;border:1px solid #dce5e2;border-radius:6px;color:#087f62;font-size:9px}.report-disclaimer{margin-top:24px;padding:25px;background:#fff8e7;border:1px solid #ead7a8;color:#765200}.report-disclaimer strong{font-size:11px}.report-disclaimer p{margin:7px 0 0;font-size:9px;line-height:1.6}
.ai-panel{display:flex;flex-direction:column;min-width:0;background:#fff;border-left:1px solid #dce6e3}.ai-panel>header{display:flex;gap:9px;align-items:center;padding:15px;border-bottom:1px solid #dce6e3}.ai-panel>header>span{display:grid;place-items:center;width:34px;height:34px;color:#fff;background:#7655df;border-radius:9px;font-size:10px}.ai-panel>header div{display:grid;gap:2px}.ai-panel header strong{font-size:11px}.ai-panel header small{color:#778780;font-size:8px}.ai-context{display:grid;gap:4px;padding:13px 15px;background:#f3f7f6;border-bottom:1px solid #dce6e3;font-size:9px}.ai-context span{color:#71817b}.suggestions{display:flex;gap:5px;overflow:auto;padding:10px 14px;border-bottom:1px solid #dce6e3}.suggestions button{flex:none;padding:6px 8px;border:1px solid #dce6e3;background:#fff;border-radius:99px;font-size:8px;cursor:pointer}.messages{flex:1;overflow:auto;padding:14px}.messages article{display:grid;grid-template-columns:25px 1fr;gap:8px;margin-bottom:14px;align-items:start}.messages article>b{display:grid;place-items:center;width:25px;height:25px;color:#fff;background:#7655df;border-radius:7px;font-size:8px}.messages article.user{display:flex;justify-content:flex-end}.messages article.user>b{display:none}.messages article.user p{max-width:78%;padding:9px 11px;background:#082d29;color:#fff;border-radius:10px 10px 2px 10px}.messages p{margin:0;font-size:9px;line-height:1.65}.ai-panel>form{padding:12px;border-top:1px solid #dce6e3}.ai-panel textarea{width:100%;height:70px;padding:10px;resize:none;border:1px solid #dce6e3;border-radius:8px;font-size:10px}.ai-panel form button{float:right;margin-top:6px;padding:7px 12px;border:0;border-radius:7px;background:#082d29;color:#fff;font-size:9px}
@media(max-width:1050px){.report-app{height:auto;min-height:100vh;overflow:visible}.report-topbar{grid-template-columns:1fr;height:auto;gap:10px;padding:14px 16px}.report-title{justify-items:start}.report-layout{display:block;height:auto}.report-toc{border-right:0;border-bottom:1px solid #dce6e3}.report-toc nav{grid-template-columns:repeat(2,minmax(0,1fr))}.report-document{overflow:visible;padding:16px}.ai-panel{border-left:0;border-top:1px solid #dce6e3}.messages{max-height:340px}.report-actions{flex-wrap:wrap}.report-brand{display:none}}@media(max-width:620px){.report-toc nav,.summary-grid,.risk-overview,.evidence-table{grid-template-columns:1fr}.cover-main h1{font-size:34px}.report-cover{min-height:560px;padding:28px}.report-section{padding:32px 22px}.section-number{font-size:34px}.cover-status{grid-template-columns:1fr}.cover-status div+div{padding-left:0;border-left:0}.locked-content{grid-template-columns:auto 1fr}.locked-content a{grid-column:2}}@media print{.report-topbar,.report-toc,.ai-panel{display:none!important}.report-app,.report-layout,.report-document{display:block;height:auto;overflow:visible;background:#fff;padding:0}.report-document{width:100%}.report-cover{min-height:100vh;break-after:page}.report-section{box-shadow:none;border:1px solid #e1e7e5;break-inside:avoid}.report-section.locked,.report-disclaimer{display:none}.evidence-table strong{font-size:10pt}.report-section>header h2{font-size:22pt}}
.report-brand{display:block;width:190px;height:52px}.report-brand img{width:100%;height:100%;object-fit:contain}
</style>
